### PR TITLE
Support multiple paths in config

### PR DESCRIPTION
**Pull request by jingweno**
For example,

```
[envdir "myapp"]
path = /etc/myapp1/env.d
path = /etc/myapp2/env.d
file-perms = 0640
path-perms = 0750
```

### CODE REVIEW

**Comment by dpiddy** [comment]
Could either the current test be expanded or a new one added to verify config.LoadConfig on a config file with multiple paths produces the expected result?

**Comment by jingweno** [comment]
> Could either the current test be expanded or a new one added to verify config.LoadConfig on a config file with multiple paths produces the expected result?

Yes, I updated the PR.

**Comment by dpiddy** [comment]
Sorry, not seeing what I was expecting: a call to config.LoadConfig somewhere on a config with two paths to verify the returned config.Config had two paths as expected.

**Comment by jingweno** [comment]
@dpiddy Ah, I see what you mean, added a test: https://github.com/heroku/json2envdir/pull/5/commits/7d7039db60a696b05f11e44af46a6b6bf778313d.

@ricardochimal Would you mind making a release if this looks okay?

**Comment by jingweno** [comment]
@ricardochimal I merged this. But I don't have access to json2envdir on packagecloud. Would you mind making a release and inviting me to the project?

**Comment by amerine** [comment]
@ricardochimal FWIW, I got @jingweno added to the packagecloud open repo.

**Pull request merged**
